language: node_js
node_js:
  - "11.1"
script:
  - npm test
  - npm run build
after_success:
  - npm run coveralls
  - npm run codacy
  - npm run codeclimate
before_deploy:
  - rm -rf dist/ast
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token:
      secure: GofVTeRDOxX0u31Xy8YxGMrqbifZkmXwLVrBFD3kpqJqxpRuml32YGcc1yJ7I2Ib6JlVpPE66EtMtvoZazT2Fx+PxPQDahbUfvT4Eekx1ljtw13hT6azAVPGsWGBvupHq9dKdQ+k6GLSFm5dAosAC6tdH2QQwbb/EvuVRBchDXZV1aRIlAFaovCZrZ2g2XDv1U9l/XMoHPw6qPChs8RVigrCxZhnIga0nRlO8TPGNb46UvmpfU3KIVHYyNp2newoAEMpVCbdbi4u3GBLS2fqQiN3ozvXupk05/VHBG4QvqTttk26WFw+FH4jkYLeefWXg79YsGXNJmeS9rDv3UyA0JHzpYk+6TM4RLr1qtYkrnogBAj5lobE0XzAmkeo2YMB/nLWR89lGIU4HsHSzhUrl7ZTTF1Fqa5BgWzkYmJ+6fVboTVpL2xFcHWeQjzzdKcVZ6p2X7aOM64b+vQ5R25vBJcZQqX6a9cUCE6cc/aDB5CbYuLFMJwTkvvdenEEc/kNR1QuOKrICBVeiqi7PCEPSBbztJhq0xY0oBrvBzbxcEVoUgQHU5512jqWEHsCECSDwPhKuYhV5pZ/ZR+841tjmvA4ZTTTGbVQndtHrxx0Jy6taJDvhM8ohPBMqKiAEoUMGJ2d2ZBhMjgH57lNR/h5pS0tZaNSSTKJNadEo0L27SA=
    on:
      branch: master
  - provider: releases
    api_key:
      secure: GofVTeRDOxX0u31Xy8YxGMrqbifZkmXwLVrBFD3kpqJqxpRuml32YGcc1yJ7I2Ib6JlVpPE66EtMtvoZazT2Fx+PxPQDahbUfvT4Eekx1ljtw13hT6azAVPGsWGBvupHq9dKdQ+k6GLSFm5dAosAC6tdH2QQwbb/EvuVRBchDXZV1aRIlAFaovCZrZ2g2XDv1U9l/XMoHPw6qPChs8RVigrCxZhnIga0nRlO8TPGNb46UvmpfU3KIVHYyNp2newoAEMpVCbdbi4u3GBLS2fqQiN3ozvXupk05/VHBG4QvqTttk26WFw+FH4jkYLeefWXg79YsGXNJmeS9rDv3UyA0JHzpYk+6TM4RLr1qtYkrnogBAj5lobE0XzAmkeo2YMB/nLWR89lGIU4HsHSzhUrl7ZTTF1Fqa5BgWzkYmJ+6fVboTVpL2xFcHWeQjzzdKcVZ6p2X7aOM64b+vQ5R25vBJcZQqX6a9cUCE6cc/aDB5CbYuLFMJwTkvvdenEEc/kNR1QuOKrICBVeiqi7PCEPSBbztJhq0xY0oBrvBzbxcEVoUgQHU5512jqWEHsCECSDwPhKuYhV5pZ/ZR+841tjmvA4ZTTTGbVQndtHrxx0Jy6taJDvhM8ohPBMqKiAEoUMGJ2d2ZBhMjgH57lNR/h5pS0tZaNSSTKJNadEo0L27SA=
    file:
      - "dist/crypto-api.js"
      - "dist/crypto-api.min.js"
      - "dist/crypto-api.min.js.map"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "nf404.name@gmail.com"
    api_key:
      secure: YlfKH2GZzvsHcDNwtzCQFBj02YrKMMQlT7tDrdJgbaBD/qzSj/yts5dBaSkEy3fD1PHK3KfFD122m4Vuc1khlQ77by9/igKvtZ80WLg2fH0MXj8DV/1I3OR10zazJv1QIiNLsCA29mmiY0nqyaQr3moVu/+ZQCBq6dkcP3imR5TZ5tuTeObKiqA7gqp/DPv/yL4WnW6Zjf+2z3smXF5/n/ow535j5P3aBv0Dkh3VBgz2/qs3pO2H3eh5LTGIBIPMlMl/l6QLRiUoSpWH1lb83dkxFVy42vNv+Y6YxBi0VbzBU4NC4oPfe9dFpCIweCaNfhAu5wBECWcdiFyY3LfrmcSJtkQ0/wDkcfbH0fRW4dZGvwQ4bTj6LdOFvJVQFIR6mch7acQ01dcUfftSBZqB5k9spkumey69TH8MHxzFTjkaq957bcKuONO+YnakhpwVv+ydRYntLuT90JDezFOaj+Qd4lz2NLSVvJtVYgiK/bcjTA47hB1QzFBlB30eaeYCIZw7XugYci5Ltc5VCADWIvhKqqVTKeDCckCV9eC7tVMTJI8e+x9xnJH2z+J8HCDo4+hHimzn6SFWLyta8huvjADr1I0uS5V2zV97rfam3NvnCLowudcxIEMmL7++xtUHdtP5JNTVE9M1gJtlF7vbyyvJGUiM6lpZWurGD20priM=
    on:
      tags: true
